export const FLOW_LANE_ORDER = [
  "design_enablement",
  "manufacturing_inputs",
  "wafer_fabrication",
  "packaging_and_test",
  "output_companies",
];

export const FLOW_LANE_META = {
  design_enablement: {
    label: "Design Enablement",
    shortLabel: "Design",
    description: "EDA and IP companies that shape the design stack before manufacturing starts.",
    color: "#7cc5c8",
    marker: "design",
    shape: "round-rectangle",
    x: 136,
  },
  manufacturing_inputs: {
    label: "Manufacturing Inputs",
    shortLabel: "Inputs",
    description: "Equipment, wafer, mask, and materials suppliers feeding the manufacturing core.",
    color: "#a7c66a",
    marker: "inputs",
    shape: "hexagon",
    x: 386,
  },
  wafer_fabrication: {
    label: "Wafer Fabrication",
    shortLabel: "Wafer Fab",
    description: "Foundry and fab nodes where upstream dependencies visibly converge.",
    color: "#f2b074",
    marker: "fabrication",
    shape: "diamond",
    x: 646,
  },
  packaging_and_test: {
    label: "Packaging and Test",
    shortLabel: "Packaging",
    description: "OSAT and packaging nodes that release usable devices out of fabrication.",
    color: "#c995d8",
    marker: "packaging",
    shape: "cut-rectangle",
    x: 926,
  },
  output_companies: {
    label: "Output Companies",
    shortLabel: "Output",
    description: "Fabless and product-side companies that depend on upstream suppliers and service partners.",
    color: "#e7868d",
    marker: "output",
    shape: "round-rectangle",
    x: 1188,
  },
};

export const DISPLAY_STAGE_ORDER = [
  "design_enablement",
  "materials_and_chemicals",
  "wafers_and_substrates",
  "masks_and_reticles",
  "manufacturing_equipment",
  "wafer_fabrication",
  "packaging_and_test",
  "device_companies",
];

export const DISPLAY_STAGE_META = {
  design_enablement: {
    label: "Design Enablement",
    shortLabel: "Design",
    description: "EDA and IP vendors shaping chip architectures and foundry-ready flows.",
    color: "#4d8d9b",
    borderColor: "#9be0e2",
    shape: "round-rectangle",
    x: 128,
  },
  materials_and_chemicals: {
    label: "Materials and Chemicals",
    shortLabel: "Materials",
    description: "Chemicals, gases, and process materials feeding the manufacturing stack.",
    color: "#5a9361",
    borderColor: "#b6e6b5",
    shape: "ellipse",
    x: 290,
  },
  wafers_and_substrates: {
    label: "Wafers and Substrates",
    shortLabel: "Wafers",
    description: "Wafer and substrate manufacturers supplying the physical base of chip production.",
    color: "#4f769f",
    borderColor: "#b8d8ff",
    shape: "ellipse",
    x: 454,
  },
  masks_and_reticles: {
    label: "Masks and Reticles",
    shortLabel: "Masks",
    description: "Photomask specialists enabling lithography and pattern transfer into the fab.",
    color: "#a9714d",
    borderColor: "#f1c89e",
    shape: "hexagon",
    x: 618,
  },
  manufacturing_equipment: {
    label: "Manufacturing Equipment",
    shortLabel: "Equipment",
    description: "Toolmakers whose process, clean, and metrology systems enable wafer fabrication.",
    color: "#7f8d46",
    borderColor: "#dae69e",
    shape: "barrel",
    x: 806,
  },
  wafer_fabrication: {
    label: "Wafer Fabrication",
    shortLabel: "Wafer Fab",
    description: "Foundries and front-end manufacturing nodes where upstream inputs converge.",
    color: "#c27744",
    borderColor: "#ffd3ac",
    shape: "diamond",
    x: 1028,
  },
  packaging_and_test: {
    label: "Packaging and Test",
    shortLabel: "Packaging",
    description: "Packaging, assembly, and test partners converting wafers into usable devices.",
    color: "#8e5c9a",
    borderColor: "#ddb7ea",
    shape: "cut-rectangle",
    x: 1248,
  },
  device_companies: {
    label: "Device Companies",
    shortLabel: "Devices",
    description: "Fabless, IDM, memory, and analog companies pulling finished chips through the chain.",
    color: "#91525d",
    borderColor: "#f2bac5",
    shape: "round-rectangle",
    x: 1464,
  },
};

export const COUNTRY_NAMES = {
  AT: "Austria",
  CA: "Canada",
  CH: "Switzerland",
  CN: "China",
  DE: "Germany",
  FR: "France",
  GB: "United Kingdom",
  HK: "Hong Kong",
  IE: "Ireland",
  IL: "Israel",
  JP: "Japan",
  KR: "South Korea",
  LU: "Luxembourg",
  MY: "Malaysia",
  NL: "Netherlands",
  SG: "Singapore",
  TH: "Thailand",
  TW: "Taiwan",
  US: "United States",
};

export const SOURCE_LABELS = {
  curated_seed: "Curated 200-company universe",
  dependency_seed: "Curated dependency seed",
  gleif: "GLEIF LEI records",
  edgar: "SEC EDGAR issuer records",
  epa_frs: "EPA facility records",
  korea_prtr: "Korea PRTR facility records",
};

export const DEFAULT_WORKSPACE_TITLE = "Semisupply Flow";
export const DEFAULT_WORKSPACE_STRAP = "Company-only dependency workspace";
