"""Default versioned taxonomy catalog for v1."""

from __future__ import annotations

from .models import TaxonomyCatalog, TaxonomyEntry, TaxonomyKind

TAXONOMY_VERSION = "v1alpha1"


def _entry(
    code: str,
    *,
    kind: TaxonomyKind,
    label: str,
    description: str,
    parent_code: str | None = None,
    aliases: tuple[str, ...] = (),
) -> TaxonomyEntry:
    return TaxonomyEntry(
        code=code,
        kind=kind,
        label=label,
        description=description,
        parent_code=parent_code,
        aliases=aliases,
    )


DEFAULT_TAXONOMY = TaxonomyCatalog(
    version=TAXONOMY_VERSION,
    entries=(
        _entry(
            "SEG.DESIGN_SOFTWARE",
            kind=TaxonomyKind.SEGMENT,
            label="Design and Software",
            description="Chip design, EDA, and licensable semiconductor IP activities.",
        ),
        _entry(
            "SEG.FRONTEND_MANUFACTURING",
            kind=TaxonomyKind.SEGMENT,
            label="Front-end Manufacturing",
            description="Wafer fabrication and front-end semiconductor manufacturing activities.",
        ),
        _entry(
            "SEG.BACKEND_MANUFACTURING",
            kind=TaxonomyKind.SEGMENT,
            label="Back-end Manufacturing",
            description="Assembly, packaging, and test activities after wafer fabrication.",
        ),
        _entry(
            "SEG.WAFERS_SUBSTRATES",
            kind=TaxonomyKind.SEGMENT,
            label="Wafers and Substrates",
            description="Silicon wafers, specialty wafers, and package substrate activities.",
        ),
        _entry(
            "SEG.MATERIALS",
            kind=TaxonomyKind.SEGMENT,
            label="Materials",
            description="Process chemicals, gases, targets, slurries, and related material inputs.",
        ),
        _entry(
            "SEG.MANUFACTURING_EQUIPMENT",
            kind=TaxonomyKind.SEGMENT,
            label="Manufacturing Equipment",
            description="Semiconductor capital equipment and equipment service activities.",
        ),
        _entry(
            "SEG.MASKS_RETICLES",
            kind=TaxonomyKind.SEGMENT,
            label="Masks and Reticles",
            description="Photomasks, mask blanks, and reticle-adjacent activities.",
        ),
        _entry(
            "SEG.POLICY_CONTROLS",
            kind=TaxonomyKind.SEGMENT,
            label="Policy and Controls",
            description="Export controls, sanctions, and policy-overlay entities or relationships.",
        ),
        _entry("ROLE.FABLESS", kind=TaxonomyKind.ROLE, label="Fabless", description="Designs chips but outsources wafer fabrication."),
        _entry("ROLE.IDM", kind=TaxonomyKind.ROLE, label="IDM", description="Integrated device manufacturer with internal fabrication capability."),
        _entry("ROLE.FOUNDRY", kind=TaxonomyKind.ROLE, label="Foundry", description="Manufactures wafers for external customers."),
        _entry(
            "ROLE.MEMORY_MANUFACTURER",
            kind=TaxonomyKind.ROLE,
            label="Memory Manufacturer",
            description="Produces memory products such as DRAM or NAND.",
        ),
        _entry(
            "ROLE.ANALOG_POWER_MANUFACTURER",
            kind=TaxonomyKind.ROLE,
            label="Analog or Power Manufacturer",
            description="Produces analog, mixed-signal, or power semiconductor products.",
        ),
        _entry("ROLE.OSAT", kind=TaxonomyKind.ROLE, label="OSAT", description="Provides outsourced semiconductor assembly and test services."),
        _entry(
            "ROLE.PACKAGING_SPECIALIST",
            kind=TaxonomyKind.ROLE,
            label="Packaging Specialist",
            description="Provides semiconductor packaging or advanced packaging capability.",
        ),
        _entry("ROLE.TEST_SERVICE", kind=TaxonomyKind.ROLE, label="Test Service", description="Provides outsourced semiconductor test services."),
        _entry(
            "ROLE.WAFER_MANUFACTURER",
            kind=TaxonomyKind.ROLE,
            label="Wafer Manufacturer",
            description="Produces base wafers or specialty wafers used in chip fabrication.",
        ),
        _entry(
            "ROLE.SUBSTRATE_MANUFACTURER",
            kind=TaxonomyKind.ROLE,
            label="Substrate Manufacturer",
            description="Produces package substrates or related substrate inputs.",
        ),
        _entry(
            "ROLE.PHOTOMASK_SUPPLIER",
            kind=TaxonomyKind.ROLE,
            label="Photomask Supplier",
            description="Produces photomasks, mask blanks, or related mask products.",
        ),
        _entry(
            "ROLE.CHEMICALS_SUPPLIER",
            kind=TaxonomyKind.ROLE,
            label="Chemicals Supplier",
            description="Supplies process chemicals or wet chemicals used in semiconductor manufacturing.",
        ),
        _entry(
            "ROLE.SPECIALTY_GASES_SUPPLIER",
            kind=TaxonomyKind.ROLE,
            label="Specialty Gases Supplier",
            description="Supplies specialty or industrial gases used in semiconductor manufacturing.",
        ),
        _entry(
            "ROLE.EQUIPMENT_SUPPLIER",
            kind=TaxonomyKind.ROLE,
            label="Equipment Supplier",
            description="Supplies semiconductor manufacturing equipment.",
        ),
        _entry("ROLE.EDA_VENDOR", kind=TaxonomyKind.ROLE, label="EDA Vendor", description="Provides electronic design automation software."),
        _entry("ROLE.IP_VENDOR", kind=TaxonomyKind.ROLE, label="IP Vendor", description="Licenses semiconductor IP blocks or cores."),
        _entry("CHIP.LOGIC", kind=TaxonomyKind.CHIP_OUTPUT, label="Logic", description="Logic chips and processor-like outputs."),
        _entry("CHIP.MEMORY", kind=TaxonomyKind.CHIP_OUTPUT, label="Memory", description="Memory chips such as DRAM or NAND."),
        _entry("CHIP.ANALOG", kind=TaxonomyKind.CHIP_OUTPUT, label="Analog", description="Analog and mixed-signal chip outputs."),
        _entry("CHIP.OTHER", kind=TaxonomyKind.CHIP_OUTPUT, label="Other", description="Other chip outputs not explicitly categorized in v1."),
        _entry("FAC.FAB", kind=TaxonomyKind.FACILITY_TYPE, label="Fab", description="Wafer fabrication site."),
        _entry("FAC.OSAT", kind=TaxonomyKind.FACILITY_TYPE, label="OSAT Facility", description="Outsourced assembly and test site."),
        _entry("FAC.PACKAGING", kind=TaxonomyKind.FACILITY_TYPE, label="Packaging Facility", description="Semiconductor package assembly site."),
        _entry("FAC.TEST", kind=TaxonomyKind.FACILITY_TYPE, label="Test Facility", description="Semiconductor test site."),
        _entry("FAC.WAFER_PLANT", kind=TaxonomyKind.FACILITY_TYPE, label="Wafer Plant", description="Wafer manufacturing site."),
        _entry(
            "FAC.SUBSTRATE_PLANT",
            kind=TaxonomyKind.FACILITY_TYPE,
            label="Substrate Plant",
            description="Package substrate manufacturing site.",
        ),
        _entry("FAC.MASK_SHOP", kind=TaxonomyKind.FACILITY_TYPE, label="Mask Shop", description="Photomask production site."),
        _entry(
            "FAC.CHEMICALS_PLANT",
            kind=TaxonomyKind.FACILITY_TYPE,
            label="Chemicals Plant",
            description="Semiconductor chemicals production site.",
        ),
        _entry("FAC.GASES_PLANT", kind=TaxonomyKind.FACILITY_TYPE, label="Gases Plant", description="Specialty gas production site."),
        _entry("FAC.RND_CENTER", kind=TaxonomyKind.FACILITY_TYPE, label="R&D Center", description="Research and development center."),
        _entry("STAGE.DESIGN", kind=TaxonomyKind.PROCESS_STAGE, label="Design", description="Chip architecture, design, and implementation."),
        _entry("STAGE.TAPEOUT", kind=TaxonomyKind.PROCESS_STAGE, label="Tapeout", description="Mask data prep and tapeout handoff."),
        _entry("STAGE.WAFER_FAB", kind=TaxonomyKind.PROCESS_STAGE, label="Wafer Fab", description="Front-end wafer manufacturing."),
        _entry("STAGE.MASKS", kind=TaxonomyKind.PROCESS_STAGE, label="Masks", description="Photomask preparation and supply."),
        _entry("STAGE.WAFER_SORT", kind=TaxonomyKind.PROCESS_STAGE, label="Wafer Sort", description="Wafer-level test and binning."),
        _entry(
            "STAGE.PACKAGE_ASSEMBLY",
            kind=TaxonomyKind.PROCESS_STAGE,
            label="Package Assembly",
            description="Package assembly and related back-end manufacturing.",
        ),
        _entry("STAGE.PACKAGE_TEST", kind=TaxonomyKind.PROCESS_STAGE, label="Package Test", description="Post-package electrical testing."),
        _entry("STAGE.FINAL_TEST", kind=TaxonomyKind.PROCESS_STAGE, label="Final Test", description="Final device testing and qualification."),
        _entry("STAGE.DISTRIBUTION", kind=TaxonomyKind.PROCESS_STAGE, label="Distribution", description="Distribution and downstream delivery."),
        _entry("ITEM.SERVICE", kind=TaxonomyKind.ITEM_CLASS, label="Service", description="Service-type supply chain input."),
        _entry("ITEM.PHYSICAL_GOOD", kind=TaxonomyKind.ITEM_CLASS, label="Physical Good", description="Physical manufactured input."),
        _entry("ITEM.SOFTWARE", kind=TaxonomyKind.ITEM_CLASS, label="Software", description="Software input or dependency."),
        _entry("ITEM.IP", kind=TaxonomyKind.ITEM_CLASS, label="IP", description="Licensable intellectual property input."),
        _entry("ITEM.DATA", kind=TaxonomyKind.ITEM_CLASS, label="Data", description="Data input or dependency."),
        _entry(
            "SERVICE.FOUNDRY_WAFER_FAB",
            kind=TaxonomyKind.SERVICE,
            label="Foundry Wafer Fab",
            description="Wafer fabrication service provided to external customers.",
            parent_code="ITEM.SERVICE",
        ),
        _entry(
            "SERVICE.MASK_MAKING",
            kind=TaxonomyKind.SERVICE,
            label="Mask Making",
            description="Mask-making service.",
            parent_code="ITEM.SERVICE",
        ),
        _entry(
            "SERVICE.PACKAGING_ASSEMBLY",
            kind=TaxonomyKind.SERVICE,
            label="Packaging Assembly",
            description="Package assembly service.",
            parent_code="ITEM.SERVICE",
        ),
        _entry(
            "SERVICE.ADVANCED_PACKAGING",
            kind=TaxonomyKind.SERVICE,
            label="Advanced Packaging",
            description="Advanced packaging service.",
            parent_code="ITEM.SERVICE",
        ),
        _entry(
            "SERVICE.TEST",
            kind=TaxonomyKind.SERVICE,
            label="Test",
            description="Semiconductor testing service.",
            parent_code="ITEM.SERVICE",
        ),
        _entry(
            "SERVICE.DESIGN_SERVICES",
            kind=TaxonomyKind.SERVICE,
            label="Design Services",
            description="Chip or design-related engineering service.",
            parent_code="ITEM.SERVICE",
        ),
        _entry(
            "SERVICE.EQUIPMENT_MAINTENANCE",
            kind=TaxonomyKind.SERVICE,
            label="Equipment Maintenance",
            description="Maintenance service for semiconductor tools.",
            parent_code="ITEM.SERVICE",
        ),
        _entry("GOOD.SILICON_WAFER", kind=TaxonomyKind.GOOD, label="Silicon Wafer", description="Base silicon wafer input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.EPI_WAFER", kind=TaxonomyKind.GOOD, label="Epi Wafer", description="Epitaxial wafer input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.SOI_WAFER", kind=TaxonomyKind.GOOD, label="SOI Wafer", description="Silicon-on-insulator wafer input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.SIC_SUBSTRATE", kind=TaxonomyKind.GOOD, label="SiC Substrate", description="Silicon carbide substrate input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.GAN_SUBSTRATE", kind=TaxonomyKind.GOOD, label="GaN Substrate", description="Gallium nitride substrate input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.PHOTOMASK", kind=TaxonomyKind.GOOD, label="Photomask", description="Photomask input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.MASK_BLANK", kind=TaxonomyKind.GOOD, label="Mask Blank", description="Mask blank input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.PHOTORESIST", kind=TaxonomyKind.GOOD, label="Photoresist", description="Photoresist material.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.WET_CHEMICAL", kind=TaxonomyKind.GOOD, label="Wet Chemical", description="Wet process chemical input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.SPECIALTY_GAS", kind=TaxonomyKind.GOOD, label="Specialty Gas", description="Specialty gas input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.CMP_SLURRY_PAD", kind=TaxonomyKind.GOOD, label="CMP Slurry or Pad", description="CMP slurry or pad input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.SPUTTER_TARGET", kind=TaxonomyKind.GOOD, label="Sputter Target", description="Sputter target input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.ABF_SUBSTRATE", kind=TaxonomyKind.GOOD, label="ABF Substrate", description="ABF package substrate input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.BT_SUBSTRATE", kind=TaxonomyKind.GOOD, label="BT Substrate", description="BT package substrate input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.LEADFRAME", kind=TaxonomyKind.GOOD, label="Leadframe", description="Leadframe packaging input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("GOOD.INTERPOSER", kind=TaxonomyKind.GOOD, label="Interposer", description="Interposer packaging input.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry(
            "GOOD.PATTERNED_WAFER",
            kind=TaxonomyKind.GOOD,
            label="Patterned Wafer",
            description="Fabricated wafer handed into downstream packaging or test flow.",
            parent_code="ITEM.PHYSICAL_GOOD",
        ),
        _entry("TOOL.LITHOGRAPHY", kind=TaxonomyKind.TOOL, label="Lithography Tool", description="Lithography equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("TOOL.ETCH", kind=TaxonomyKind.TOOL, label="Etch Tool", description="Etch equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("TOOL.DEPOSITION", kind=TaxonomyKind.TOOL, label="Deposition Tool", description="Deposition equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("TOOL.CMP", kind=TaxonomyKind.TOOL, label="CMP Tool", description="CMP equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("TOOL.IMPLANT", kind=TaxonomyKind.TOOL, label="Implant Tool", description="Implant equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("TOOL.CLEAN", kind=TaxonomyKind.TOOL, label="Clean Tool", description="Clean equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry(
            "TOOL.METROLOGY_INSPECTION",
            kind=TaxonomyKind.TOOL,
            label="Metrology or Inspection Tool",
            description="Metrology or inspection equipment.",
            parent_code="ITEM.PHYSICAL_GOOD",
        ),
        _entry("TOOL.THERMAL", kind=TaxonomyKind.TOOL, label="Thermal Tool", description="Thermal processing equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry("TOOL.TEST_EQUIPMENT", kind=TaxonomyKind.TOOL, label="Test Equipment", description="Semiconductor test equipment.", parent_code="ITEM.PHYSICAL_GOOD"),
        _entry(
            "TOOL.PACKAGING_EQUIPMENT",
            kind=TaxonomyKind.TOOL,
            label="Packaging Equipment",
            description="Packaging equipment.",
            parent_code="ITEM.PHYSICAL_GOOD",
        ),
        _entry("SW.EDA", kind=TaxonomyKind.SOFTWARE, label="EDA Software", description="Electronic design automation software.", parent_code="ITEM.SOFTWARE"),
        _entry("IP.CPU_CORE", kind=TaxonomyKind.IP, label="CPU Core IP", description="CPU core intellectual property.", parent_code="ITEM.IP"),
        _entry("IP.GPU_CORE", kind=TaxonomyKind.IP, label="GPU Core IP", description="GPU core intellectual property.", parent_code="ITEM.IP"),
        _entry(
            "IP.NPU_ACCELERATOR",
            kind=TaxonomyKind.IP,
            label="NPU Accelerator IP",
            description="NPU accelerator intellectual property.",
            parent_code="ITEM.IP",
        ),
        _entry("IP.SERDES", kind=TaxonomyKind.IP, label="SerDes IP", description="SerDes intellectual property.", parent_code="ITEM.IP"),
        _entry(
            "IP.MEMORY_INTERFACE",
            kind=TaxonomyKind.IP,
            label="Memory Interface IP",
            description="Memory interface intellectual property.",
            parent_code="ITEM.IP",
        ),
        _entry("OWNS", kind=TaxonomyKind.PREDICATE, label="Owns", description="Ownership relationship."),
        _entry("SUBSIDIARY_OF", kind=TaxonomyKind.PREDICATE, label="Subsidiary Of", description="Subsidiary relationship."),
        _entry("JOINT_VENTURE_WITH", kind=TaxonomyKind.PREDICATE, label="Joint Venture With", description="Joint venture relationship."),
        _entry("OPERATES_FACILITY", kind=TaxonomyKind.PREDICATE, label="Operates Facility", description="Facility operator relationship."),
        _entry(
            "FACILITY_LOCATED_IN",
            kind=TaxonomyKind.PREDICATE,
            label="Facility Located In",
            description="Facility-to-country anchoring relationship.",
        ),
        _entry("FACILITY_HAS_STATUS", kind=TaxonomyKind.PREDICATE, label="Facility Has Status", description="Facility status relationship."),
        _entry(
            "SUPPLIES_MATERIAL_TO",
            kind=TaxonomyKind.PREDICATE,
            label="Supplies Material To",
            description="Explicit material supply relationship.",
        ),
        _entry(
            "SUPPLIES_COMPONENT_TO",
            kind=TaxonomyKind.PREDICATE,
            label="Supplies Component To",
            description="Explicit component supply relationship.",
        ),
        _entry(
            "PROVIDES_EQUIPMENT_TO",
            kind=TaxonomyKind.PREDICATE,
            label="Provides Equipment To",
            description="Explicit equipment supply relationship.",
        ),
        _entry(
            "PROVIDES_SERVICE_TO",
            kind=TaxonomyKind.PREDICATE,
            label="Provides Service To",
            description="Explicit service relationship.",
        ),
        _entry("FABRICATES_FOR", kind=TaxonomyKind.PREDICATE, label="Fabricates For", description="Explicit foundry manufacturing relationship."),
        _entry("PACKAGES_FOR", kind=TaxonomyKind.PREDICATE, label="Packages For", description="Explicit packaging relationship."),
        _entry("TESTS_FOR", kind=TaxonomyKind.PREDICATE, label="Tests For", description="Explicit testing relationship."),
        _entry("LICENSES_IP_TO", kind=TaxonomyKind.PREDICATE, label="Licenses IP To", description="Explicit IP licensing relationship."),
        _entry("PROVIDES_PDK_TO", kind=TaxonomyKind.PREDICATE, label="Provides PDK To", description="Explicit PDK relationship."),
        _entry("USES_EQUIPMENT_FROM", kind=TaxonomyKind.PREDICATE, label="Uses Equipment From", description="Tool usage relationship."),
        _entry("SUPPLIES_TO", kind=TaxonomyKind.PREDICATE, label="Supplies To", description="Generic supplier-to-customer relationship."),
        _entry("DEPENDS_ON", kind=TaxonomyKind.PREDICATE, label="Depends On", description="General dependency relationship."),
        _entry(
            "HAS_SINGLE_SOURCE_RISK_FROM",
            kind=TaxonomyKind.PREDICATE,
            label="Has Single-Source Risk From",
            description="Single-source concentration relationship.",
        ),
        _entry(
            "EXPOSED_TO_EXPORT_CONTROL",
            kind=TaxonomyKind.PREDICATE,
            label="Exposed To Export Control",
            description="Export-control or sanctions exposure relationship.",
        ),
    ),
)
